CREATE OR REPLACE VIEW zz_equipment_start AS
SELECT
EQUIPMENT_CHANGE.VISIT_ID AS VISIT_ID,
EQUIPMENT_CHANGE.START_INVENTORY_ID AS START_ID,
START.SERIAL_NUMBER AS START_SERIAL,
START.EQUIPMENT_TYPE AS START_TYPE,
START.MAKE AS START_MAKE,
START.MODEL AS START_MODEL
FROM (
  EQUIPMENT_CHANGE 
  LEFT JOIN
  EQUIPMENT_INVENTORY 
  START 
  ON
    (
      (
      START.INVENTORY_ID = EQUIPMENT_CHANGE.START_INVENTORY_ID
      )
    )
  )