CREATE OR REPLACE VIEW zz_odn_depth_raw AS
SELECT
  TOWS_RAW.TOW_ID,
  TOWS_RAW.TIMESTAMP,
  TOWS_RAW.LATITUDE,
  TOWS_RAW.LONGITUDE,
  TOWS_RAW.TR_VALUE AS DEPTH,
  TOWS.VESSEL_ID,
  vessel_gear.FMCODE
FROM 
  TOWS_RAW
INNER JOIN 
  TOWS
ON 
  TOWS.TOW_ID=TOWS_RAW.TOW_ID
  INNER JOIN
    vessel_gear
  ON 
  TOWS.VESSEL_ID=vessel_gear.VESSEL_ID
WHERE 
  TOWS_RAW.TR_PARAMETER = 'DEPTH' AND TOWS.VESSEL_ID = 26
;