/*
* Title: view_vessel_loggers.sql
* Author: George Maynard
* Contact: george.maynard@noaa.gov
* Purpose: To create a view called `vessel_loggers` that shows every logger
*   assignment that's been recorded in the database
*/
CREATE OR REPLACE VIEW zz_vessel_loggers AS
SELECT 
  EQUIPMENT_INVENTORY.INVENTORY_ID,
  EQUIPMENT_INVENTORY.MAKE,
  EQUIPMENT_INVENTORY.MODEL,
  EQUIPMENT_INVENTORY.SERIAL_NUMBER,
  VESSELS.VESSEL_NAME,
  VESSELS.PORT,
  VESSELS.VESSEL_ID,
  CONTACTS.FIRST_NAME,
  CONTACTS.LAST_NAME
FROM
    VESSELS
    INNER JOIN
      CONTACTS 
      INNER JOIN 
        EQUIPMENT_INVENTORY 
      ON CONTACTS.CONTACT_ID = EQUIPMENT_INVENTORY.CUSTODIAN
    ON VESSELS.PRIMARY_CONTACT = CONTACTS.CONTACT_ID
WHERE EQUIPMENT_TYPE = 'LOGGER' AND CURRENT_LOCATION = 'VESSEL' AND VESSEL_NAME != 'KATHRYN MARIE'
ORDER BY VESSEL_NAME
;